export the submodules properly
This commit fixes the two following errors:
```
nu_scripts  nightly [✓] > use . misc edit
Error: nu::parser::export_not_found

  × Export not found.
   ╭─[entry #2:1:1]
 1 │ use . misc edit
   ·       ──┬─
   ·         ╰── could not find imports
   ╰────
```
```
nu_scripts  nightly [✓] x use scripts/misc.nu edit
Error: nu::parser::module_not_found

  × Module not found.
    ╭─[~/.local/share/git/store/github.com/goatfiles/nu_scripts/scripts/misc.nu:10:1]
 10 │ #*
 11 │ use scripts/prompt.nu
    ·     ────────┬────────
    ·             ╰── module not found
 12 │
    ╰────
  help: module files and their paths must be available before your script is run as parsing occurs before anything is evaluated
```

Now we do not need to add the path to the root of the
`goatfiles/nu_scripts` to have them working.

Commands used:
```
"export module scripts/community.nu
export module scripts/docker.nu
export module scripts/dotfiles.nu
export module scripts/downloads.nu
export module scripts/env.nu
export module scripts/gf.nu
export module scripts/gpg.nu
export module scripts/hx.nu
export module scripts/ipfs.nu
export module scripts/job.nu
export module scripts/misc.nu
export module scripts/plugin.nu
export module scripts/shell_prompt.nu
export module scripts/ssh.nu
export module scripts/sys.nu
export module scripts/trash.nu
export module scripts/venv.nu
export module scripts/vm.nu
export module scripts/xdg.nu" | save --force mod.nu

sd "use scripts/" "use " scripts/*
```